# Generated by Django 5.2 on 2025-05-06 14:20

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='health_record',
            field=models.FileField(blank=True, null=True, upload_to='health_records/', validators=[core.validators.file_validators, django.core.validators.FileExtensionValidator('pdf')]),
        ),
    ]
