# Generated by Django 5.2 on 2025-04-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liscence_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
