# Generated by Django 5.2 on 2025-09-01 18:27

import cloudinary.models
import core.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 2), validators=[core.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='user',
            name='health_record',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[core.validators.file_validators], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[core.validators.validate_image], verbose_name='image'),
        ),
    ]
