# Generated by Django 5.2 on 2025-09-01 19:09

import core.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_date_of_birth_alter_user_health_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalpracticioner',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 9), validators=[core.validators.validate_future_dob]),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 2), validators=[core.validators.validate_future_dob]),
        ),
    ]
