# Generated by Django 5.2 on 2025-05-16 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_health_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=10, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('matched', models.BooleanField(default=False)),
                ('token_activation_code', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
