# Generated by Django 5.2 on 2025-04-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_address_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPracticioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liscence_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('liscence_expiry_date', models.DateField()),
            ],
        ),
    ]
