# Generated by Django 5.2 on 2025-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Non-binary', 'Non-binary'), ('Undefine', 'Prefer not to say')], max_length=20),
        ),
    ]
