# Generated by Django 5.2 on 2025-04-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medicalpracticioner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalpracticioner',
            old_name='liscence_expiry_date',
            new_name='licsence_expiry_date',
        ),
        migrations.RenameField(
            model_name='medicalpracticioner',
            old_name='liscence_number',
            new_name='licsence_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='liscence_expiry_date',
            new_name='licsence_expiry_date',
        ),
    ]
