# Generated by Django 5.2 on 2025-05-05 16:16

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='health_record',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[core.validators.file_validators, django.core.validators.FileExtensionValidator('pdf', 'img', 'jpg')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[core.validators.file_validators]),
        ),
    ]
