# Generated by Django 5.2 on 2025-04-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_liscence_expiry_date_medicalpracticioner_licsence_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalpracticioner',
            old_name='licsence_expiry_date',
            new_name='liscence_expiry_date',
        ),
        migrations.RenameField(
            model_name='medicalpracticioner',
            old_name='licsence_number',
            new_name='liscence_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='licsence_expiry_date',
            new_name='liscence_expiry_date',
        ),
    ]
