# Generated by Django 5.2 on 2025-04-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_licsence_expiry_date_medicalpracticioner_liscence_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalpracticioner',
            name='id',
        ),
        migrations.AlterField(
            model_name='medicalpracticioner',
            name='liscence_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
