# Generated by Django 5.2 on 2025-04-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_medicalpracticioner_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalpracticioner',
            old_name='liscence_expiry_date',
            new_name='license_expiry_date',
        ),
        migrations.RenameField(
            model_name='medicalpracticioner',
            old_name='liscence_number',
            new_name='license_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='liscence_expiry_date',
            new_name='license_expiry_date',
        ),
    ]
