# Generated by Django 5.2 on 2025-05-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_liscence_expiry_date_medicalpracticioner_license_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalpracticioner',
            name='speciality',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
