# Generated by Django 5.2 on 2025-05-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_medicalpracticioner_speciality_user_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_med',
            field=models.BooleanField(default=False),
        ),
    ]
