# Generated by Django 5.2 on 2025-08-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_rename_confirmation_sent_at_appointment_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0, help_text='Day of the week for the appointment (0=Sunday, 6=Saturday)'),
        ),
    ]
