# Generated by Django 5.2 on 2025-08-13 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_remove_appointment_appointment_doctor__e7d63f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_doctor__ba10d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_cancell_a5ec4f_idx',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='notes',
            new_name='cancellation_reason',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'time', 'is_active')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'date', 'time', 'is_active'], name='appointment_doctor__995dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['is_active'], name='appointment_is_acti_54c2a8_idx'),
        ),
    ]
